apiVersion: v1
kind: Service
metadata:
  name: mynginx
  labels:
    run: mynginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
    protocol: TCP
  selector:
    run: mynginx
