apiVersion: v1
kind: Service
metadata:
  name: mynginx
  labels:
    run: mynginx
spec:
  type: NodePort
  ports:
  - port: 32453
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: mynginx
